### ISSUE TITLE
`correct_typos` does not work with `var_group` rule (validator)

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/deductive#3]
The following does not work (version 1.0.1)

```R
library(deductive)
## correct_typos should expand var_group
v <- validator(
  pos := var_group(x),
  pos = pos > 0,
  lin = x + y == 20
)

dat <- data.frame( x = 21, y = 8)
tinytest::expect_equivalent( data.frame(x = 12,y = 8)
                           , correct_typos(dat, v)
                           )
```

Thanks to @reijeridema for reporting!

The issue is similar to #2 , but probably has implications for `validate`. 
The method `<validator>$linear_coefficients()` does not allow for expanding groups and assignments, but it should (by default IMHO).

**Comment by reijeridema** [comment]
On further investigation the problem seems to be in the expansion of the assigment rule `pos := var_group(x)`.
